name: Automl notebooks
# This workflow is triggered on pull request to the repository.
on:
  pull_request:
    branches:
      - master
    paths:
      - 00_Setup_AML_Workspace.ipynb
      - 01_Data_Preparation.ipynb
      - Automated_ML/**
env:
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  WORKSPACE_PREFIX: "github-ci-ws"
  WORKSPACE_REGION: ${{ secrets.WORKSPACE_REGION }}
  AZUREML_SERVICE_PRINCIPAL_TENANT_ID: ${{ secrets.AZUREML_SERVICE_PRINCIPAL_TENANT_ID }}
  AZUREML_SERVICE_PRINCIPAL_ID: ${{ secrets.AZUREML_SERVICE_PRINCIPAL_ID }}
  AZUREML_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZUREML_SERVICE_PRINCIPAL_PASSWORD }}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  setup-and-train:
    name: Run automl python notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install -r Automated_ML/requirements.txt
      - name: Convert notebooks to python
        run: |
          jupyter nbconvert --to script 00_Setup_AML_Workspace.ipynb
          jupyter nbconvert --to script 01_Data_Preparation.ipynb
          jupyter nbconvert --to script Automated_ML/02_AutoML_Training_Pipeline/02_AutoML_Training_Pipeline.ipynb
          jupyter nbconvert --to script Automated_ML/03_AutoML_Forecasting_Pipeline/03_AutoML_Forecasting_Pipeline.ipynb
      - name: Login via Az module
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: Setup workspace
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $Env:WORKSPACE_NAME = "$Env:WORKSPACE_PREFIX-$Env:PR_NUMBER"
            echo "************************************"
            echo "Using workspace: $Env:WORKSPACE_NAME"
            echo "************************************"
            python 00_Setup_AML_Workspace.py
            $resource = Get-AzResource -Name $Env:WORKSPACE_NAME -ResourceGroupName $Env:RESOURCE_GROUP
            $expirationTime = (Get-Date).AddHours(24).ToUniversalTime()
            New-AzTag -ResourceId $resource.id -Tag @{"expiresOn"=$expirationTime}
          azPSVersion: 'latest'
      - name: Data preparation
        run: |
          ipython 01_Data_Preparation.py
      - name: Run training
        run: |
          cd Automated_ML/02_AutoML_Training_Pipeline
          python 02_AutoML_Training_Pipeline.py
      - name: Run prediction
        run: |
          cd Automated_ML/03_AutoML_Forecasting_Pipeline
          python 03_AutoML_Forecasting_Pipeline.py
