name: Custom script notebooks
# This workflow is triggered on pull request to the repository.
on: pull_request
env:
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  WORKSPACE_PREFIX: "github-ci-pipeline"
  WORKSPACE_REGION: ${{ secrets.WORKSPACE_REGION }}
  AZUREML_SERVICE_PRINCIPAL_TENANT_ID: ${{ secrets.AZUREML_SERVICE_PRINCIPAL_TENANT_ID }}
  AZUREML_SERVICE_PRINCIPAL_ID: ${{ secrets.AZUREML_SERVICE_PRINCIPAL_ID }}
  AZUREML_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZUREML_SERVICE_PRINCIPAL_PASSWORD }}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  setup-and-train:
    name: Run custom script python notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install -r Custom_Script/requirements.txt
      - name: Convert notebooks to python
        run: |
          jupyter nbconvert --to script 00_Setup_AML_Workspace.ipynb
          jupyter nbconvert --to script Custom_Script/01_Data_Preparation.ipynb
          jupyter nbconvert --to script Custom_Script/02_Training_Pipeline.ipynb
          jupyter nbconvert --to script Custom_Script/03_Forecasting_Pipeline.ipynb
      - name: Login via Az module
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $Env:WORKSPACE_NAME = "$Env:WORKSPACE_PREFIX-$Env:PR_NUMBER"
            echo "Using workspace ${WORKSPACE_NAME}"
            python 00_Setup_AML_Workspace.py
            $resource = Get-AzResource -Name $Env:WORKSPACE_NAME -ResourceGroupName $Env:RESOURCE_GROUP
            $time = Get-Date
            $utcTime = $time.ToUniversalTime()
            New-AzTag -ResourceId $resource.id -Tag @{"modified"=$utcTime}
          azPSVersion: 'latest'
      - name: Data preparation
        run: |
          cd Custom_Script
          python 01_Data_Preparation.py
      - name: Run training
        run: |
          cd Custom_Script
          python 02_Training_Pipeline.py
      - name: Run prediction
        run: |
          cd Custom_Script
          python 03_Forecasting_Pipeline.py
